# src/app/localization/en.py

TRANSLATIONS = {
    'welcome': 'Welcome',
    'goodbye': 'Goodbye',
    'home.title': 'FaraidFlow',
    'home.subtitle': 'Faraid Calculator',
    'calculate': 'Calculate',
    'information': 'Information',
    'about': 'About',
    'soon.calculate': 'Coming soon: Calculate',
    'soon.information': 'Coming soon: Information',
    'soon.about': 'Coming soon: About',
    'language.title': 'Language',
    'language.tooltip': 'Change language',
    'calc.title': 'Inheritance Calculator',
    'calc.back': 'Back',
    'calc.estate': 'Estate',
    'calc.heirs': 'Heirs',
    'calc.tree': 'Inheritance tree',
    'calc.spouse': 'Spouse',
    'calc.children': 'Children',
    'calc.parents': 'Parents',
    'calc.siblings': 'Siblings',
    'calc.spouse_none': 'No spouse',
    'calc.count': 'Count',
    'husband': 'Husband',
    'wife': 'Wife',
    'son': 'Sons',
    'daughter': 'Daughters',
    'father': 'Father',
    'mother': 'Mother',
    'brother_full': 'Full brother',
    'sister_full': 'Full sister',
    'brother_consang': 'Paternal half-brother',
    'sister_consang': 'Paternal half-sister',
    'brother_uterine': 'Maternal half-brother',
    'sister_uterine': 'Maternal half-sister',
    'calc.calculate': 'Calculate',
    'calc.deceased': 'The Deceased',
    'calc.col_heir': 'Heir',
    'calc.col_share': 'Share',
    'calc.col_amount': 'Amount',
    'calc.col_each': 'Per Person',
    'calc.col_total': 'Total Amount',
    'calc.details': 'Calculation details',
    'calc.equal': '=',
    'calc.breakdown': 'Breakdown',
    'calc.gross': 'Value of assets',
    'calc.funeral': 'Funeral costs',
    'calc.debts': 'Debts',
    'calc.wasiat': 'Wasiat',
    'calc.net': 'Net to distribute',
    'calc.wasiat_cap': '(1/3 cap)',
    'calc.wasiat_exc': 'excess',
    'calc.aul': 'Shares exceeded the estate - base raised {old} to {new}.',
    'calc.radd': 'Remainder returned to fixed-share heirs (spouse excluded).',
    'calc.asabah': 'Remainder taken by: {names}.',
    'calc.unassigned': 'Remainder left unassigned (only a spouse remains) \u2014 consult a scholar.',
    'calc.blocked': 'Excluded',
    'calc.blocked_tip': 'Excluded: {reason}',
    'calc.block.reason.lineal': 'excluded by a son or the father',
    'calc.block.reason.full_brother': 'excluded by a full brother',
    'calc.block.reason.uterine': 'excluded by son, daughter, or father',
    'calc.residual': 'Residual left unallocated after rounding: {amount}.',
    'calc.debt_note': 'Debts are not inherited - they attach to the estate and are settled before the remainder is shared. Heirs are not required to pay them but may do so.',
    'calc.wasiat_warn': 'Wasiat exceeds one third of the estate.',
    'calc.wasiat_consent': 'A wasiat above one third is only enforceable with the heirs\' consent.',
    'calc.depleted': 'All assets are used up and there is still debt of about {amount}. Heirs are not required to pay it, but may choose to.',
    'calc.nothing': 'There is nothing left to distribute.',
    'calc.errors.no_heirs': 'Select at least one heir.',
    'calc.errors.spouse_both': 'Cannot choose both husband and wife.',
    'money.prefix': '$',
    'money.thousands_sep': ',',
    'money.decimal_sep': '.',
    'settings.title': 'Settings',
    'settings.language': 'Language',
    'settings.currency': 'Currency',
    'settings.theme': 'Theme',
    'currency.usd': 'US Dollar (USD)',
    'currency.idr': 'Indonesian Rupiah (IDR)',
    'currency.myr': 'Malaysian Ringgit (MYR)',
    'currency.eur': 'Euro (EUR)',
    'currency.sgd': 'Singapore Dollar (SGD)',
    'theme.light': 'Light',
    'theme.dark': 'Dark',
    'theme.system': 'System',
    'info.title': 'Information',
    'info.intro.title': 'Introduction',
    'info.intro.body': 'Faraid is the Islamic law of inheritance that determines how a deceased Muslim\'s estate is distributed among heirs. This calculator applies the standard faraid methodology used in many jurisdictions.',
    'info.legal_basis.title': 'Legal Basis',
    'info.legal_basis.quran': 'Qur\'an: An-Nisa 4:11-12, 4:176',
    'info.legal_basis.hadith': 'Hadith: Sahih Bukhari 6732, Sahih Muslim 1615 (faraid is half of knowledge)',
    'info.how_it_works.title': 'How It Works',
    'info.how_it_works.body': 'Enter the estate value and funeral costs, debts, and wasiat (bequest). Then select the surviving heirs. The calculator applies faraid rules: fixed shares first, then residue to asabah. Special cases like \'aul (base increase) and radd (return) are handled automatically.',
    'info.glossary.title': 'Glossary',
    'info.glossary.wasiat': 'Wasiat \u2014 A bequest of up to one third of the estate to non-heirs.',
    'info.glossary.hajb': 'Hajb \u2014 Exclusion of an heir by another heir who is closer in relationship.',
    'info.glossary.aul': '\u2018Aul \u2014 Total fixed shares exceed the estate; all shares are reduced proportionally.',
    'info.glossary.radd': 'Radd \u2014 Remainder returned to fixed-share heirs (spouse excluded) when no asabah exists.',
    'info.glossary.asabah': 'Asabah \u2014 Residuary heirs who take the remainder after fixed shares are satisfied.',
    'info.glossary.pewaris': 'Pewaris \u2014 The deceased person whose estate is being distributed.',
    'info.glossary.ahli_waris': 'Ahli Waris \u2014 Heirs entitled to inherit under faraid.',
    'info.disclaimer.title': 'Disclaimer',
    'info.disclaimer.body': 'This tool is for educational purposes only and does not constitute legal or religious advice. Consult a qualified scholar or ahli faraid for actual cases.',
    'about.title': 'About',
    'about.author': 'Author',
    'about.location': 'Location',
    'about.credits': 'Credits',
    'about.license': 'License',
    'about.github': 'GitHub',
    'about.donate': 'Donate',
    'about.donate_soon': 'Coming in a future update',
}