# src/app/localization/en.py

TRANSLATIONS = {
    'welcome': 'Welcome',
    'goodbye': 'Goodbye',
    'home.title': 'FaraidFlow',
    'home.subtitle': 'Islamic Inheritance Calculator',
    'calculate': 'Calculate',
    'information': 'Information',
    'about': 'About',
    'soon.calculate': 'Coming soon: Calculate',
    'soon.information': 'Coming soon: Information',
    'soon.about': 'Coming soon: About',
    'language.title': 'Language',
    'language.tooltip': 'Change language',
    'calc.title': 'Inheritance Calculator',
    'calc.back': 'Back',
    'calc.estate': 'Estate',
    'calc.heirs': 'Heirs',
    'calc.tree': 'Inheritance tree',
    'calc.spouse': 'Spouse',
    'calc.children': 'Children',
    'calc.parents': 'Parents',
    'calc.siblings': 'Siblings',
    'calc.spouse_none': 'No spouse',
    'calc.count': 'Count',
    'husband': 'Husband',
    'wife': 'Wife',
    'son': 'Son',
    'daughter': 'Daughter',
    'father': 'Father',
    'mother': 'Mother',
    'brother_full': 'Full brother',
    'sister_full': 'Full sister',
    'brother_consang': 'Paternal brother',
    'sister_consang': 'Paternal sister',
    'brother_uterine': 'Maternal brother',
    'sister_uterine': 'Maternal sister',
    'calc.calculate': 'Calculate',
    'calc.deceased': 'Deceased',
    'calc.col_heir': 'Heir',
    'calc.col_share': 'Share',
    'calc.col_amount': 'Amount',
    'calc.col_each': 'Each',
    'calc.col_total': 'Total',
    'calc.details': 'Calculation details',
    'calc.equal': '=',
    'calc.breakdown': 'Breakdown',
    'calc.gross': 'Value of assets',
    'calc.funeral': 'Funeral costs',
    'calc.debts': 'Debts',
    'calc.wasiat': 'Wasiat',
    'calc.net': 'Net to distribute',
    'calc.wasiat_cap': '(1/3 cap)',
    'calc.wasiat_exc': 'excess',
    'calc.aul': 'Shares exceeded the estate - base raised {old} to {new}.',
    'calc.radd': 'Remainder returned to fixed-share heirs (spouse excluded).',
    'calc.asabah': 'Remainder taken by: {names}.',
    'calc.unassigned': 'Remainder left unassigned (only a spouse remains) - seek legal/fiqh guidance.',
    'calc.blocked': 'Blocked',
    'calc.blocked_tip': 'Blocked: {reason}',
    'calc.block.reason.lineal': 'excluded by a son or the father',
    'calc.block.reason.full_brother': 'excluded by a full brother',
    'calc.block.reason.uterine': 'excluded by son, daughter, or father',
    'calc.residual': 'Residual left unallocated after rounding: {amount}.',
    'calc.debt_note': 'Debts are not inherited - they attach to the estate and are settled before the remainder is shared. Heirs are not required to pay them but may do so.',
    'calc.wasiat_warn': 'Wasiat exceeds one third of the estate.',
    'calc.wasiat_consent': 'A wasiat above one third is only enforceable with the heirs\' consent.',
    'calc.depleted': 'All assets are used up and there is still debt of about {amount}. Heirs are not required to pay it, but may choose to.',
    'calc.nothing': 'There is nothing left to distribute.',
    'calc.errors.no_heirs': 'Select at least one heir.',
    'calc.errors.spouse_both': 'Cannot choose both husband and wife.',
    'money.prefix': '$',
    'money.thousands_sep': ',',
    'money.decimal_sep': '.',
}