# src/app/localization/id.py

TRANSLATIONS = {
    'welcome': 'Selamat datang',
    'goodbye': 'Selamat tinggal',
    'home.title': 'FaraidFlow',
    'home.subtitle': 'Kalkulator Faraid',
    'calculate': 'Hitung',
    'information': 'Informasi',
    'about': 'Tentang',
    'soon.calculate': 'Segera hadir: Hitung',
    'soon.information': 'Segera hadir: Informasi',
    'soon.about': 'Segera hadir: Tentang',
    'language.title': 'Bahasa',
    'language.tooltip': 'Ganti bahasa',
    'calc.title': 'Kalkulator Waris',
    'calc.back': 'Kembali',
    'calc.estate': 'Harta Peninggalan',
    'calc.heirs': 'Ahli Waris',
    'calc.tree': 'Pohon Waris',
    'calc.spouse': 'Pasangan',
    'calc.children': 'Anak',
    'calc.parents': 'Orang Tua',
    'calc.siblings': 'Saudara',
    'calc.spouse_none': 'Tidak ada pasangan',
    'calc.count': 'Jumlah',
    'husband': 'Suami',
    'wife': 'Istri',
    'son': 'Anak laki',
    'daughter': 'Anak perempuan',
    'father': 'Ayah',
    'mother': 'Ibu',
    'brother_full': 'Saudara kandung',
    'sister_full': 'Saudari kandung',
    'brother_consang': 'Saudara seayah',
    'sister_consang': 'Saudari seayah',
    'brother_uterine': 'Saudara seibu',
    'sister_uterine': 'Saudari seibu',
    'calc.calculate': 'Hitung',
    'calc.deceased': 'Pewaris',
    'calc.col_heir': 'Ahli Waris',
    'calc.col_share': 'Bagian',
    'calc.col_amount': 'Jumlah',
    'calc.col_each': 'Tiap orang',
    'calc.col_total': 'Total',
    'calc.details': 'Rincian perhitungan',
    'calc.equal': '=',
    'calc.breakdown': 'Rincian',
    'calc.gross': 'Nilai aset',
    'calc.funeral': 'Biaya pemakaman',
    'calc.debts': 'Utang',
    'calc.wasiat': 'Wasiat',
    'calc.net': 'Sisa yang dibagi',
    'calc.wasiat_cap': '(batas 1/3)',
    'calc.wasiat_exc': 'kelebihan',
    'calc.aul': 'Bagian melebihi harta - pokok masalah dinaikkan {old} menjadi {new}.',
    'calc.radd': 'Sisa dikembalikan kepada ahli waris yang berhak mendapat bagian (pasangan dikecualikan).',
    'calc.asabah': 'Sisa diambil oleh: {names}.',
    'calc.unassigned': 'Sisa tidak dialokasikan (hanya pasangan tersisa) \u2014 konsultasikan dengan ahli faraid.',
    'calc.blocked': 'Terhalang',
    'calc.blocked_tip': 'Terhalang: {reason}',
    'calc.block.reason.lineal': 'terhalang oleh anak laki-laki atau ayah',
    'calc.block.reason.full_brother': 'terhalang oleh saudara kandung laki-laki',
    'calc.block.reason.uterine': 'terhalang oleh anak atau ayah',
    'calc.residual': 'Sisa tidak teralokasi setelah pembulatan: {amount}.',
    'calc.debt_note': 'Utang bukan warisan - utang melekat pada harta peninggalan dan diselesaikan sebelum sisa dibagikan. Ahli waris tidak wajib membayar, tetapi boleh.',
    'calc.wasiat_warn': 'Wasiat melebihi sepertiga harta.',
    'calc.wasiat_consent': 'Wasiat di atas sepertiga hanya sah dengan persetujuan ahli waris.',
    'calc.depleted': 'Seluruh harta habis dan masih ada utang sekitar {amount}. Ahli waris tidak wajib membayar, tetapi boleh jika mau.',
    'calc.nothing': 'Tidak ada sisa yang dapat dibagi.',
    'calc.errors.no_heirs': 'Pilih minimal satu ahli waris.',
    'calc.errors.spouse_both': 'Tidak dapat memilih suami sekaligus istri.',
    'calc.empty_hint': 'Jalankan perhitungan untuk melihat hasil di sini.',
    'money.prefix': '$',
    'money.thousands_sep': '.',
    'money.decimal_sep': ',',
    'settings.title': 'Pengaturan',
    'settings.language': 'Bahasa',
    'settings.currency': 'Mata Uang',
    'settings.theme': 'Tema',
    'currency.usd': 'Dolar AS (USD)',
    'currency.idr': 'Rupiah Indonesia (IDR)',
    'currency.myr': 'Ringgit Malaysia (MYR)',
    'currency.eur': 'Euro (EUR)',
    'currency.sgd': 'Dolar Singapura (SGD)',
    'theme.light': 'Terang',
    'theme.dark': 'Gelap',
    'theme.system': 'Sistem',
    'info.title': 'Informasi',
    'info.intro.title': 'Pengantar',
    'info.intro.body': 'Faraid adalah hukum waris Islam yang menentukan bagaimana harta peninggalan seorang Muslim dibagikan di antara ahli waris. Kalkulator ini menerapkan metodologi faraid standar yang digunakan di banyak yurisdiksi.',
    'info.legal_basis.title': 'Dasar Hukum',
    'info.legal_basis.quran': 'Qur\'an: An-Nisa 4:11-12, 4:176',
    'info.legal_basis.hadith': 'Hadits: Shahih Bukhari 6732, Shahih Muslim 1615 (faraid adalah separuh ilmu)',
    'info.how_it_works.title': 'Cara Kerja',
    'info.how_it_works.body': 'Masukkan nilai harta peninggalan dan biaya pemakaman, utang, serta wasiat. Kemudian pilih ahli waris yang masih hidup. Kalkulator menerapkan aturan faraid: bagian tetap terlebih dahulu, lalu sisa untuk asabah. Kasus khusus seperti \'aul (penaikan pokok) dan radd (pengembalian) ditangani secara otomatis.',
    'info.glossary.title': 'Istilah',
    'info.glossary.wasiat': 'Wasiat \u2014 Wasiat hingga sepertiga harta peninggalan kepada bukan ahli waris.',
    'info.glossary.hajb': 'Hajb \u2014 Penghalangan ahli waris oleh ahli waris lain yang lebih dekat hubungan nasabnya.',
    'info.glossary.aul': '\u2018Aul \u2014 Total bagian tetap melebihi harta; semua bagian dikurangi secara proporsional.',
    'info.glossary.radd': 'Radd \u2014 Sisa dikembalikan kepada ahli waris berhak bagian (pasangan dikecualikan) bila tidak ada asabah.',
    'info.glossary.asabah': 'Asabah \u2014 Ahli waris sisa yang mengambil sisa harta setelah bagian tetap terpenuhi.',
    'info.glossary.pewaris': 'Pewaris \u2014 Orang yang meninggal dunia dan harta peninggalannya dibagikan.',
    'info.glossary.ahli_waris': 'Ahli Waris \u2014 Orang yang berhak mewarisi menurut faraid.',
    'info.disclaimer.title': 'Penafian',
    'info.disclaimer.body': 'Alat ini hanya untuk tujuan edukasi dan tidak merupakan nasihat hukum atau agama. Konsultasikan dengan ahli faraid yang berkualifikasi untuk kasus nyata.',
    'about.title': 'Tentang',
    'about.author': 'Penulis',
    'about.location': 'Lokasi',
    'about.credits': 'Kredit',
    'about.license': 'Lisensi',
    'about.github': 'GitHub',
    'about.donate': 'Donasi',
    'about.donate_soon': 'Hadir di pembaruan mendatang',
}