# src/app/localization/id.py

TRANSLATIONS = {
    'welcome': 'Selamat datang',
    'goodbye': 'Selamat tinggal',
    'home.title': 'FaraidFlow',
    'home.subtitle': 'Ahli Waris',
    'calculate': 'Hitung',
    'information': 'Informasi',
    'about': 'Tentang',
    'soon.calculate': 'Segera hadir: Hitung',
    'soon.information': 'Segera hadir: Informasi',
    'soon.about': 'Segera hadir: Tentang',
    'language.title': 'Bahasa',
    'language.tooltip': 'Ganti bahasa',
    'calc.title': 'Kalkulator Waris',
    'calc.back': 'Kembali',
    'calc.estate': 'Harta Peninggalan',
    'calc.heirs': 'Ahli Waris',
    'calc.spouse': 'Pasangan',
    'calc.children': 'Anak',
    'calc.parents': 'Orang Tua',
    'calc.siblings': 'Saudara',
    'calc.spouse_none': 'Tidak ada pasangan',
    'calc.count': 'Jumlah',
    'husband': 'Suami',
    'wife': 'Istri',
    'son': 'Anak laki-laki',
    'daughter': 'Anak perempuan',
    'father': 'Ayah',
    'mother': 'Ibu',
    'brother_full': 'Saudara kandung',
    'sister_full': 'Saudari kandung',
    'brother_consang': 'Saudara seayah',
    'sister_consang': 'Saudari seayah',
    'brother_uterine': 'Saudara seibu',
    'sister_uterine': 'Saudari seibu',
    'calc.calculate': 'Hitung',
    'calc.deceased': 'Pewaris',
    'calc.col_heir': 'Ahli Waris',
    'calc.col_share': 'Bagian',
    'calc.col_amount': 'Jumlah',
    'calc.breakdown': 'Rincian',
    'calc.gross': 'Nilai aset',
    'calc.funeral': 'Biaya pemakaman',
    'calc.debts': 'Utang',
    'calc.wasiat': 'Wasiat',
    'calc.net': 'Sisa yang dibagi',
    'calc.wasiat_cap': '(batas 1/3)',
    'calc.wasiat_exc': 'kelebihan',
    'calc.aul': 'Bagian melebihi harta - pokok masalah dinaikkan {old} menjadi {new}.',
    'calc.radd': 'Sisa dikembalikan kepada ahli waris berbagian (pasangan dikecualikan).',
    'calc.asabah': 'Sisa diambil oleh: {names}.',
    'calc.unassigned': 'Sisa tidak dialokasikan (hanya pasangan tersisa) - rujuk hukum/ahli faraidh.',
    'calc.rounded': 'Jumlah dibulatkan ke Rupiah terdekat.',
    'calc.debt_note': 'Utang bukan warisan - utang melekat pada harta peninggalan dan diselesaikan sebelum sisa dibagikan. Ahli waris tidak wajib membayar, tetapi boleh.',
    'calc.wasiat_warn': 'Wasiat melebihi sepertiga harta.',
    'calc.wasiat_consent': 'Wasiat di atas sepertiga hanya sah dengan persetujuan ahli waris.',
    'calc.depleted': 'Seluruh harta habis dan masih ada utang sekitar Rp{amount}. Ahli waris tidak wajib membayar, tetapi boleh jika mau.',
    'calc.nothing': 'Tidak ada sisa yang dapat dibagi.',
    'calc.errors.no_heirs': 'Pilih minimal satu ahli waris.',
    'calc.errors.wife_max': 'Maksimal 4 istri.',
    'calc.errors.spouse_both': 'Tidak dapat memilih suami sekaligus istri.',
}